[package]
name = "dr-rustario"
authors = ["Alex Haslehurst"]
version = "1.0.0"
edition = "2021"
resolver = "2"

[package.metadata.vcpkg]
git = "https://github.com/microsoft/vcpkg"
tag = "2024.10.21"
dependencies = ["sdl2", "sdl2-image", "sdl2-gfx", "sdl2-mixer", "sdl2-ttf"]

[package.metadata.vcpkg.target]
x86_64-pc-windows-msvc = { triplet = "x64-windows-static-md" }

[features]
default = ["pkgconfig"]
vcpkg = ["sdl2/static-link", "sdl2/use-vcpkg"]
pkgconfig = ["sdl2/use-pkgconfig"]
retro_handheld = []

[build-dependencies]
built = { version = "0.8.1", default-features = false, features = [] }
embed-resource = "3.0.11"

[dev-dependencies]
mockall = "0.15.0"

[dependencies]
rand = "0.10.2"
rand_chacha = "0.10.0"
serde = { version = "1.0.229", default-features = false, features = ["derive"] }
sdl2 = { version = "0.38.0", default-features = false, features = ["image","mixer","ttf"] }
confy = { version = "2.0.0", default-features = false, features = ["yaml_conf"] }
num-format = "0.4.4"
strum = { version = "0.28.0", features = ["derive"] }
strum_macros = "0.28.0"
titlecase = "3.6.0"

[profile.release]
strip = "symbols"
